name: Tests

on: [push]

env:
  DEVELOPER_DIR: /Applications/Xcode_11.3.app/Contents/Developer

jobs:

  macos:
    runs-on: macOS-latest
    name: macOS
    steps:
      - uses: actions/checkout@v1
      - run: swift build
