name: Tests

on: [push]

env:
  DEVELOPER_DIR: /Applications/Xcode_11.3.app/Contents/Developer

jobs:

  ubuntu:
    runs-on: ubuntu-latest
    container:
     image: swift:5.1
    steps:
     - uses: actions/checkout@v1
     - run: swift build

  macos:
    runs-on: macOS-latest
    name: macOS
    steps:
      - uses: actions/checkout@v1
      - run: swift build
